### ISSUE TITLE
Fail to detect internet connection

### ISSUE THREAD

**Issue by davidsarkany** [HMBSbige/shadowsocksr-docker#1]
Hi!

I tried use this docker image, but i got error.
`Fail to detect internet connection: Error code: #404`

**Server command**
`docker run -it -d --restart=always --name=ssr --dns 1.1.1.1 --dns 8.8.8.8 -p 8080:8080 -p 8080:8080/udp hmbsbige/shadowsocksr-docker:latest -s 0.0.0.0 -p 8080 -k 123456 -m none -O auth_chain_d -G 1#1:HMBSbige -o tls1.2_ticket_auth_compatible -t 300 --fast-open --workers 1`

**Android client**
Galaxy S7 Edge
shadowsocksr-android-3.6.0-fix.apk from [here](https://github.com/HMBSbige/ShadowsocksR-Android/releases)
I tried copy the logcat, but the app crashed.

Settings
![Screenshot_20200322-005619_ShadowsocksR](https://user-images.githubusercontent.com/9111944/77239284-45b84180-6bd9-11ea-86f7-6e7a54bace31.jpg)

Error screen
![Screenshot_20200322-005759_ShadowsocksR](https://user-images.githubusercontent.com/9111944/77239283-40f38d80-6bd9-11ea-9657-99b0da29f0ad.jpg)

**Comment by HMBSbige** [comment]
Wrong protocol param

**Comment by davidsarkany** [comment]
@HMBSbige What is the correct protocol param?
